// This file contains TypeScript types that match your Supabase database schema
// These types are automatically generated by the Supabase CLI

export type Json =
  | string
  | number
  | boolean
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
    type Json =
      | string
      | number
      | boolean
      | { [key: string]: Json | undefined }
      | Json[]

    interface Tables {
      profiles: {
        Row: {
          id: string
          username: string
          avatar_url: string | null
          total_score: number
          highest_level_reached: number
          games_played: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          username: string
          avatar_url?: string | null
          total_score?: number
          highest_level_reached?: number
          games_played?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          username?: string
          avatar_url?: string | null
          total_score?: number
          highest_level_reached?: number
          games_played?: number
          created_at?: string
          updated_at?: string
        }
      }
      questions: {
        Row: {
          id: string
          question_text: string
          option_a: string
          option_b: string
          option_c: string
          option_d: string
          correct_option: number
          difficulty: number
          category: string
          created_by: string | null
          is_approved: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          question_text: string
          option_a: string
          option_b: string
          option_c: string
          option_d: string
          correct_option: number
          difficulty: number
          category: string
          created_by?: string | null
          is_approved?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          question_text?: string
          option_a?: string
          option_b?: string
          option_c?: string
          option_d?: string
          correct_option?: number
          difficulty?: number
          category?: string
          created_by?: string | null
          is_approved?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      games: {
        Row: {
          id: string
          user_id: string
          score: number
          level_reached: number
          questions_answered: number
          correct_answers: number
          lifelines_used: Json
          completed_at: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          score?: number
          level_reached?: number
          questions_answered?: number
          correct_answers?: number
          lifelines_used?: Json
          completed_at?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          score?: number
          level_reached?: number
          questions_answered?: number
          correct_answers?: number
          lifelines_used?: Json
          completed_at?: string | null
          created_at?: string
        }
      }
    }

    interface View {
      leaderboard: {
        Row: {
          id: string
          username: string | null
          avatar_url: string | null
          score: number
          level_reached: number
          created_at: string
          rank: number
        }
      }
    }
  }
}
